version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  api-web-crawler:
    build:
      context: .
      dockerfile: apps/api-web-crawler/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_NAME: ${QUEUE_NAME}

    ports:
      - "3000:3000"
  crawler-worker:
    build:
      context: .
      dockerfile: apps/crawler-worker/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_NAME: ${QUEUE_NAME}
    platform: linux/amd64
    ports:
      - "3001:3001"

volumes:
  postgres-data:
  redis-data:
